### PR TITLE
`pod lib lint` is failing

### PR DESCRIPTION
**Pull request by farktronix**
`pod lib lint` is failing with these errors and warnings:

```
   Testing with `xcodebuild`. 
 -> RealmConverter (0.5.3)
    - ERROR | swift: Specification `RealmConverter` specifies inconsistent `swift_versions` (`5.0`) compared to the one present in your `.swift-version` file (`3`). Please remove the `.swift-version` file which is now deprecated and only use the `swift_versions` attribute within your podspec.
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | [OSX] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'Realm/core/realm-sync.xcframework realm-sync library macos-x86_64' for the current build architectures (arm64 x86_64).
    - NOTE  | xcodebuild:  ld: warning: directory not found for option '-L/Users/pharkas/Library/Developer/Xcode/DerivedData/App-asmewyhnuikzkmglxcvabhvcalpd/Build/Products/Release/XCFrameworkIntermediates/realm-sync'
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [OSX] xcodebuild:  ld: warning: dylib (/Users/pharkas/Library/Developer/Xcode/DerivedData/App-asmewyhnuikzkmglxcvabhvcalpd/Build/Products/Release/SSZipArchive/SSZipArchive.framework/SSZipArchive) was built for newer macOS version (10.8) than being linked (10.7)
    - NOTE  | [OSX] xcodebuild:  warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'TGSpreadsheetWriter' from project 'Pods')
    - NOTE  | [OSX] xcodebuild:  warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'SSZipArchive' from project 'Pods')
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'PathKit' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'CSwiftV' from project 'Pods')

[!] RealmConverter did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
```

There appear to be three problems here:
1. A swift version is defined in `.swift-version`, which isn't necessary any more
  - This is a simple fix
 2. Realm 10.0 doesn't build for `arm64`. This should be fixed with Cocoapods 1.10 and Realm 10.1 (per [this issue](https://github.com/realm/realm-cocoa/issues/6785)) but I'm still seeing the error during `pod lib lint` even with those versions on my machine.
  - **I'm still working on a fix for this**
 3. Most of the dependencies have a lower MacOS or iOS deployment target than RealmConverter, which creates warnings. 
  - We can fix this in our Podfile, but it's not possible to fix it in the pod spec since that would require overwriting build settings for other Cocoapods in a workspace.

### CODE REVIEW

**Comment by farktronix** [comment]
@pavel-ship-it Let me know if you have any ideas on the Realm arm64 issue. You might have some ideas since you worked on that issue in the Realm repository.

**Comment by pavel-ship-it** [comment]
Hi @farktronix I haven't look in to this problem yet. Just a message I'm not forget about this pull request.

**Review by pavel-ship-it — APPROVED** [review]
LGTM.
I can build all versions locally, pod lib lint has passed.

**Comment by pavel-ship-it** [comment]
Hi @farktronix ,
RealmConverter 0.5.4 is published. Thank you for help. 👍

**Pull request merged**
