### PR TITLE
Fix CSV export crash while exporting an empty object array

### PR DESCRIPTION
**Pull request by stel**
This PR is addressed to https://github.com/realm/realm-browser-osx/issues/180.

/cc @jpsim @TimOliver

### CODE REVIEW

**Comment by jpsim** [comment]
Implementation changes look good. How about writing a unit test that would have triggered the bug before?

**Comment by jpsim** [comment]
@stel looks like you forgot about this one.

**Comment by stel** [comment]
No, I didn't, this one is in my list but with lower priority than "some other test" :)

Anyway thanks for reminding me, #17 contains this test.

**Comment by jpsim** [comment]
👍 with #17

**Pull request merged**
