### PR TITLE
Update Realm to 2.8.3

### PR DESCRIPTION
**Pull request by stel**

### CODE REVIEW

**Comment by stel** [comment]
Something has been changed after updating to the latest Realm version, got `failed: caught "NSInvalidArgumentException", "-[RLM:Unmanaged businesses count]: unrecognized selector sent to instance 0x7fce6836d370"` (see https://travis-ci.org/realm/realm-cocoa-converter/builds/251117057?utm_source=github_status&utm_medium=notification), when adding unmanaged object to Realm.

**Comment by bdash** [comment]
@stel, the crash you're seeing stems from the fact that [the runtime-generated Objective-C classes used by the importer have a bogus implementation of `-respondsToSelector:`](https://github.com/realm/realm-cocoa-converter/blob/caf865290b3ca8f6b91d7d9070abd8e69c1085e1/RealmConverter/Importer/DataImporter.swift#L113-L117) that always returns true. This means that when Realm interrogates the object to determine if it's array-like (`respondsToSelector:@selector(objectAtIndex:)`) or dictionary-like (`respondsToSelector:@selector(objectForKey:)`), it gets a bogus answer.

I'm not clear why the implementation of `-respondsToSelector:` exists. The tests all appear to pass after removing it.

**Comment by stel** [comment]
Thanks for investigating this, @bdash! Probably it's just a kind of legacy support for the previous versions. Wonder why it's started reproducing only now.

**Comment by bdash** [comment]
I think this would have started when Realm Cocoa v2.7 changed to using the object store's object accessor implementation, because as part of that we started using `-respondsToSelector:` to determine how to interpret values. Prior to that release we did relied on type checks.

**Pull request merged**
