### PR TITLE
Added Travis Support

### PR DESCRIPTION
**Pull request by TimOliver**
I've enabled this project on Travis and added the appropriate Travis YML file.

### CODE REVIEW

**Comment by jpsim** [comment]
Doesn't work because the `RealmConverter` scheme isn't shared:

> xcodebuild: error: The workspace named "RealmConverter" does not contain a scheme named "RealmConverter". The "-list" option can be used to find the names of the schemes in the workspace.

**Comment by jpsim** [comment]
Also concerning that Travis marked this as passing despite it producing that error.

**Comment by TimOliver** [comment]
Really? I tried running the command locally and it built and tested fine on my local machine.
I'll make a proper issue tracking this and look into it.

**Comment by jpsim** [comment]
The Xcode GUI typically autogenerates schemes when opening a project, but that doesn't happen with plain `xcodebuild`.

**Pull request merged**
